# Ejercicios sobre diccionarios II + Ficheros

## Ejercicio 1

El fichero [localidades.txt]() contiene información de las localidades de la Comunidad de Madrid. Los datos que contiene son:
* Nombre de la localidad
* Teléfono Ayuntamiento
* Teléfono Información
* Teléfono emergencias

Aunque los teléfonos pueden no aparecer todos en el fichero.
Crear una función llamada __leer_datos__ que lea los datos del fichero y los almacene en una lista de líneas. Usa la operación __readlines__ de los ficheros. El parámetro de entrada de la función es la ruta donde se encuentra el fichero. 

La función debe devolver una lista con todos los municipio leídos en el fichero.
¿ Cuantos municipios hay en el fichero ?

In [2]:
# Sol:
f = open('localidades.txt', encoding="utf8")
l = f.readlines()

In [3]:
def leer_localidades():
    f = open('localidades.txt', encoding="utf8")
    l = f.readlines()
    localidades = []
    for linea in l[1:]:
        datos = linea.split('|')
        localidades.append(datos[0])
    return localidades

In [4]:
leer_localidades()

['La Acebeda',
 'Ajalvir',
 'El Álamo',
 'Alcalá de Henares',
 'Alcobendas',
 'Alcorcón',
 'Aldea del Fresno',
 'Alpedrete',
 'Ambite',
 'Anchuelo',
 'Aranjuez',
 'Arganda del Rey',
 'Arroyomolinos',
 'El Atazar',
 'Batres',
 'Becerril de la Sierra',
 'Belmonte de Tajo',
 'El Berrueco',
 'Berzosa del Lozoya',
 'Boadilla del Monte',
 'El Boalo',
 'Brea de Tajo',
 'Brunete',
 'Buitrago del Lozoya',
 'Bustarviejo',
 'Cabanillas de la Sierra',
 'La Cabrera',
 'Cadalso de los Vidrios',
 'Camarma de Esteruelas',
 'Campo Real',
 'Canencia',
 'Carabaña',
 'Casarrubuelos',
 'Cenicientos',
 'Cercedilla',
 'Cervera de Buitrago',
 'Chapinería',
 'Chinchón',
 'Ciempozuelos',
 'Cobeña',
 'Collado Mediano',
 'Collado Villalba',
 'Colmenar de Oreja',
 'Colmenar del Arroyo',
 'Colmenar Viejo',
 'Coslada',
 'Cubas de la Sagra',
 'El Escorial',
 'Estremera',
 'Fresnedillas de la Oliva',
 'Fresno de Torote',
 'Fuenlabrada',
 'Fuente el Saz de Jarama',
 'Fuentidueña de Tajo',
 'Garganta de los Montes',
 'G

In [5]:
def quitar_saltos(lista):
    lista2 = []
    i = 0
    while i < len(lista):
        x = lista[i].rstrip()
        lista2.append(x[0:])
        i = i + 1
    return (lista2)

In [6]:
quitar_saltos(l)

['Nombre localidad|Teléfono Ayuntamiento|Teléfono Información | Teléfono emergencias',
 'La Acebeda|9286 |2855 |',
 'Ajalvir||9097 |',
 'El Álamo|9375 |8420 |',
 'Alcalá de Henares|8350 ||7261',
 'Alcobendas||3115 |',
 'Alcorcón|||9861',
 'Aldea del Fresno|||4043',
 'Alpedrete|1705 |6251 |2198',
 'Ambite||9037 |',
 'Anchuelo|4973 |5257 |',
 'Aranjuez||4805 |',
 'Arganda del Rey|3111 ||3035',
 'Arroyomolinos|2926 ||8481',
 'El Atazar|9650 |7157 |',
 'Batres|8800 |1164 |6059',
 'Becerril de la Sierra||7251 |1875',
 'Belmonte de Tajo|||3419',
 'El Berrueco|2476 ||6650',
 'Berzosa del Lozoya|4787 |2913 |2478',
 'Boadilla del Monte|1428 |5557 |',
 'El Boalo|5632 |8008 |8019',
 'Brea de Tajo|||8496',
 'Brunete|3731 |8510 |',
 'Buitrago del Lozoya|6917 |2243 |3178',
 'Bustarviejo||6323 |5048',
 'Cabanillas de la Sierra||8537 |',
 'La Cabrera||7061 |',
 'Cadalso de los Vidrios|1525 ||3811',
 'Camarma de Esteruelas||6306 |',
 'Campo Real|5948 ||6869',
 'Canencia||3642 |',
 'Carabaña|7429 |3229 

In [7]:
def leer_datos(lista):
    lista2 = []
    i = 1
    while i < len(lista):
        x = lista[i].split('|')
        lista2.append(x[0:4])
        i = i + 1
    print(len(lista2))
    return (lista2)

In [8]:
l3 = leer_datos(l2)

161


In [9]:
type(l3)

list

In [7]:
l3

[['La Acebeda', '9286 ', '2855 ', ''],
 ['Ajalvir', '', '9097 ', ''],
 ['El Álamo', '9375 ', '8420 ', ''],
 ['Alcalá de Henares', '8350 ', '', '7261'],
 ['Alcobendas', '', '3115 ', ''],
 ['Alcorcón', '', '', '9861'],
 ['Aldea del Fresno', '', '', '4043'],
 ['Alpedrete', '1705 ', '6251 ', '2198'],
 ['Ambite', '', '9037 ', ''],
 ['Anchuelo', '4973 ', '5257 ', ''],
 ['Aranjuez', '', '4805 ', ''],
 ['Arganda del Rey', '3111 ', '', '3035'],
 ['Arroyomolinos', '2926 ', '', '8481'],
 ['El Atazar', '9650 ', '7157 ', ''],
 ['Batres', '8800 ', '1164 ', '6059'],
 ['Becerril de la Sierra', '', '7251 ', '1875'],
 ['Belmonte de Tajo', '', '', '3419'],
 ['El Berrueco', '2476 ', '', '6650'],
 ['Berzosa del Lozoya', '4787 ', '2913 ', '2478'],
 ['Boadilla del Monte', '1428 ', '5557 ', ''],
 ['El Boalo', '5632 ', '8008 ', '8019'],
 ['Brea de Tajo', '', '', '8496'],
 ['Brunete', '3731 ', '8510 ', ''],
 ['Buitrago del Lozoya', '6917 ', '2243 ', '3178'],
 ['Bustarviejo', '', '6323 ', '5048'],
 ['Cabanillas 

## Ejercicio 2

Escribe una función llamada __crear_agenda__ para crear la agenda de los teléfonos de los municipios de la Comunidad de Madrid.
La función tiene un único parámetro de entrada, que es la lista de municipios devuelta por la función del Ejercicio 1. 

El valor devuelto por la función __crear_agenda__ es de tipo diccionario, donde las claves son los nombres de los municipios y el valor asociado a cada clave será otro diccionario con tantas claves como teléfonos disponibles tenga el municipio.

__Notas:__
La función deve devolver un diccionario con el siguiente aspecto:

```
{
 'La Acebeda': {'Teléfono Ayuntamiento': '9286',   'Teléfono Información': '2855'},
 'Ajalvir': {'Teléfono Información': '9097'},
 'El Álamo': {'Teléfono Ayuntamiento': '9375', 'Teléfono Información': '8420'},
 'Alcalá de Henares': {'Teléfono Ayuntamiento': '8350',   'Teléfono Emergencias': '7261'},
 'Alcobendas': {'Teléfono Información': '3115'},
    ...
    ...
 'Zarzalejo': {'Teléfono Ayuntamiento': '5046',  'Teléfono Información': '1283'}
}
```

In [10]:
def crear_agenda(lista):
    dicc_nuevo = {}
    i = 0
    lista1 = ['Teléfono Ayuntamiento','Teléfono Información','Teléfono emergencias'] # las claves
    while i < len(lista):
        lista2 = [lista[i][1],lista[i][2],lista[i][3]] # los valores de las claves
        if lista[i][1] == '': # quitar los que estén vacíos
            lista2.remove(lista[i][1])
        if lista[i][2] == '':
            lista2.remove(lista[i][2])
        if lista[i][3] == '':
            lista2.remove(lista[i][3])
        dicc_nuevo[lista[i][0]]= dict(zip(lista1,lista2))
        i = i+1
    return (dicc_nuevo)

In [11]:
agenda_municipios = crear_agenda(l3)
agenda_municipios

{'La Acebeda': {'Teléfono Ayuntamiento': '9286 ',
  'Teléfono Información': '2855 '},
 'Ajalvir': {'Teléfono Ayuntamiento': '9097 '},
 'El Álamo': {'Teléfono Ayuntamiento': '9375 ',
  'Teléfono Información': '8420 '},
 'Alcalá de Henares': {'Teléfono Ayuntamiento': '8350 ',
  'Teléfono Información': '7261'},
 'Alcobendas': {'Teléfono Ayuntamiento': '3115 '},
 'Alcorcón': {'Teléfono Ayuntamiento': '9861'},
 'Aldea del Fresno': {'Teléfono Ayuntamiento': '4043'},
 'Alpedrete': {'Teléfono Ayuntamiento': '1705 ',
  'Teléfono Información': '6251 ',
  'Teléfono emergencias': '2198'},
 'Ambite': {'Teléfono Ayuntamiento': '9037 '},
 'Anchuelo': {'Teléfono Ayuntamiento': '4973 ',
  'Teléfono Información': '5257 '},
 'Aranjuez': {'Teléfono Ayuntamiento': '4805 '},
 'Arganda del Rey': {'Teléfono Ayuntamiento': '3111 ',
  'Teléfono Información': '3035'},
 'Arroyomolinos': {'Teléfono Ayuntamiento': '2926 ',
  'Teléfono Información': '8481'},
 'El Atazar': {'Teléfono Ayuntamiento': '9650 ',
  'Teléfo

## Ejercicio 3 

Escribe una función en Python llamada __consulta_telefono__ para recuperar los teléfonos disponibles de un municipio.
La función tiene dos argumentos de entrada:
1. Agenda de municipios creada por la función del ejercicio 2.
2. Nombre de un municipio

Si el nombre del municipio  no se encuentra en el diccionario, la función devuelve el valor `False`. En caso contrario, devuelve un diccionario con los teléfonos disponibles.

__Ejemplo de ejecución:__

``` 
In: 
    t = consulta_telefono('Zarzalejo', agenda_municipios)
    t
Out:
    {'Teléfono Ayuntamiento': '5046',  'Teléfono Información': '1283'}
```


In [12]:
def consulta_telefono(municipio,agenda):
    if municipio in agenda:
        return agenda[municipio]
    else:
        return False

In [13]:
t = consulta_telefono('Zarzalejo', agenda_municipios)
t

{'Teléfono Ayuntamiento': '5046 ', 'Teléfono Información': '1283 '}

## Ejercicio 4

Escribe una función en Python llamada __consulta_tipo_telef__ para recuperar número de teléfono de un determinado tipo (Emergencias, Ayuntamiento o Información) de un municipio.
La función tiene tres argumentos de entrada:
1. Agenda de los municipios
2. Nombre de un municipio
3. Tipo de número de teléfono

Si el municipio no se encuentra en la agenda, la función devuelve el valor `False`. En caso contrario, devuelve su número de teléfono. Si el tipo de teléfono no existe para ese amigo, la función devuelve el valor `False`.

__Ejemplo de ejecución 1 :__

``` 
In: 
    t =  consulta_tipo_telefono('Zarzalejo', 'Teléfono Ayuntamiento', agenda_municipios)
    t
Out:
    5046
```
__Ejemplo de ejecución 2 :__
``` 
In: 
    t =  consulta_tipo_telefono('Zarzalejo', 'Teléfono Piscina', agenda_municipios)
    t
Out:
    False
```



In [14]:
def consulta_tipo_telefono(municipio, tipo_telefono, agenda):
    if municipio in agenda and tipo_telefono in agenda[municipio]:
        return agenda[municipio][tipo_telefono]
    else:
        return False

In [15]:
consulta_tipo_telefono('Zarzalejo', 'Teléfono Piscina', agenda_municipios)

False

## Ejercicio 5

Escribe una función en Python llamada __lista_municipios__ para recuperar los nombres de los municipios que se encuentrasn registrados en la agenda de teléfonos.
La función tiene un único argumento de entrada:
1. Diccionario que representa la agenda

La función ha de devolver una lista ordenada de municipios en orden lexicográfico.

__Ejemplo de ejecución:__
``` 
In: 
    a = lista_municipios(agenda)
    a
Out:
    ['Ajalvir',
     'Alcalá de Henares',
     'Alcobendas', 
     ...
     'Zarzalejo']

```

In [16]:
def lista_municipios(agenda):
    a = sorted(list(agenda))
    return a

In [17]:
lista_municipios(agenda_municipios)

['Ajalvir',
 'Alcalá de Henares',
 'Alcobendas',
 'Alcorcón',
 'Aldea del Fresno',
 'Alpedrete',
 'Ambite',
 'Anchuelo',
 'Aranjuez',
 'Arganda del Rey',
 'Arroyomolinos',
 'Batres',
 'Becerril de la Sierra',
 'Belmonte de Tajo',
 'Berzosa del Lozoya',
 'Boadilla del Monte',
 'Brea de Tajo',
 'Brunete',
 'Buitrago del Lozoya',
 'Bustarviejo',
 'Cabanillas de la Sierra',
 'Cadalso de los Vidrios',
 'Camarma de Esteruelas',
 'Campo Real',
 'Canencia',
 'Carabaña',
 'Casarrubuelos',
 'Cenicientos',
 'Cercedilla',
 'Cervera de Buitrago',
 'Chapinería',
 'Chinchón',
 'Ciempozuelos',
 'Cobeña',
 'Collado Mediano',
 'Collado Villalba',
 'Colmenar Viejo',
 'Colmenar de Oreja',
 'Colmenar del Arroyo',
 'Coslada',
 'Cubas de la Sagra',
 'El Atazar',
 'El Berrueco',
 'El Boalo',
 'El Escorial',
 'El Molar',
 'El Vellón',
 'El Álamo',
 'Estremera',
 'Fresnedillas de la Oliva',
 'Fresno de Torote',
 'Fuenlabrada',
 'Fuente el Saz de Jarama',
 'Fuentidueña de Tajo',
 'Garganta de los Montes',
 'Garg

## Ejercicio 6

Escribe una función en Python llamada __eliminar_municipio__ para eliminar los datos de un municipio de una agenda de teléfonos. Dicha agenda se representa como un diccionario. 
La función tiene tres  argumentos de entrada:
1. Diccionario que representa la agenda
2. El nombre de un municipio

La función devuelve el valor `True` si se ha eliminado correctamente. Devuelve False para indicar que el municipio no estaba en la agenda.


In [18]:
def eliminar_municipio(agenda, municipio):
    if municipio in agenda:
        agenda.pop(municipio)
        return True
    else:
        return False

In [19]:
eliminar_municipio(agenda_municipios, 'Brea de Tajo')

True

In [20]:
eliminar_municipio(agenda_municipios, 'Viveiro')

False

## Ejercicio 7

Escribe una función en Python llamada __nuevo_telefono_amigo__ para insertar un nuevo tipo de teléfono de un  amigo en una agenda de teléfonos. Dicha agenda se representa como un diccionario. 
La función tiene cuatro  argumentos de entrada:
1. Diccionario donde los elementos son de la forma `nombre`: {`tipo`:`num_teléfono`, ... } 
2. El nombre del amigo
3. Su teléfono
4. Tipo del teléfono (casa, movil, etc)

La función devuleve el valor `True` si la inserción ha ido bien. Devuelve False en caso contrario (el amigo ya existe, o ya existe ese tipo de teléfono).

__Ejemplo de ejecución 1:__
``` 
In: 
    agenda = {'Ana': {'casa':111, 'movil': 1111}, 'Pedro': {'movil':222, 'trabajo':22222}, 'Luis': {'casa': 458}}
    b, nuevo_telefono_amigo('Luis',333, 'movil', agenda)
    b, agenda
Out:
    (True,
     {'Ana': {'casa': 111, 'movil': 1111},
      'Pedro': {'movil': 222, 'trabajo': 22222},
      'Luis': {'casa': 458, 'movil': 333}}
```

__Ejemplo de ejecución 2:__
``` 
In: 
    agenda = {'Ana': {'casa':111, 'movil': 1111}, 'Pedro': {'movil':222, 'trabajo':22222}, 'Luis': {'casa': 458}}
    b, nuevo_telefono_amigo('Bea',7777, 'movil', agenda)
    b, agenda
Out:
    (True,
     {'Ana': {'casa': 111, 'movil': 1111},
      'Pedro': {'movil': 222, 'trabajo': 22222},
      'Luis': {'casa': 458},
      'Bea': {'movil': 7777}}
```

In [5]:
agenda = {'Ana': {'casa':111, 'movil': 1111}, 'Pedro': {'movil':222, 'trabajo':22222}, 'Luis': {'casa': 458}}
agenda

{'Ana': {'casa': 111, 'movil': 1111},
 'Pedro': {'movil': 222, 'trabajo': 22222},
 'Luis': {'casa': 458}}

In [2]:
def nuevo_telefono_amigo(nombre,telefono,tipo_telefono,diccionario):
    if nombre in diccionario:
        if tipo_telefono in nombre:
            return (False, diccionario)
        else:
            diccionario[nombre].update({tipo_telefono:telefono})
            return (True, diccionario)
    else:
        diccionario.update({nombre:{tipo_telefono:telefono}})
        return (True,diccionario)

In [6]:
nuevo_telefono_amigo('Luis',333, 'movil', agenda)

(True,
 {'Ana': {'casa': 111, 'movil': 1111},
  'Pedro': {'movil': 222, 'trabajo': 22222},
  'Luis': {'casa': 458, 'movil': 333}})

In [7]:
nuevo_telefono_amigo('Bea',7777, 'movil', agenda)

(True,
 {'Ana': {'casa': 111, 'movil': 1111},
  'Pedro': {'movil': 222, 'trabajo': 22222},
  'Luis': {'casa': 458, 'movil': 333},
  'Bea': {'movil': 7777}})

--------------------